[package]
name = "ffs"
description = "Fabulous Fabrication System: C/C++ package manager and build tool"
author = "Iannis de Zwart"

[dependencies]
toml = "https://github.com/marzer/tomlplusplus"

[targets.ffs]
src = [
	"main.cpp",
	"build.cpp",
	"config.cpp",
	"help.cpp",
	"install.cpp",
	"util.cpp"
]